version: "3.8"

services:
  apache:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    depends_on:
      - nextjs

  nextjs:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: npm start
